language: node_js
node_js:
  - '4.5.0'

services:
  - mongodb

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - exportDISPLAY=:99.0
  - sh-e/etc/init.d/xvfbstart

script: mocha --compilers jsx:babel-register -R list

notifications:
 email: false
 slack: hr46:9wx63tFQsFOqK9t4TaCE4FUM