language: node_js
node_js:
  - '6.5.0'

services:
  - mongodb

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

script: ./node_modules/mocha/bin/mocha test

notifications:
 email: false
 slack: hr46:9wx63tFQsFOqK9t4TaCE4FUM